SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720
PLAYER_RADIUS = 20 # The Radius of the Player's Ship
LINE_WIDTH = 2 # The width of the lines that draw the player's ship
PLAYER_TURN_SPEED = 300
PLAYER_SPEED = 200
# For asteroids
ASTEROID_MIN_RADIUS = 20
ASTEROID_KINDS = 3
ASTEROID_SPAWN_RATE_SECONDS = 0.8
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS